# Generated by Django 3.2.5 on 2022-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_alter_recipie_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapRecipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipieurl', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imageurl', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ('title', 'description'),
            },
        ),
    ]
