# Generated by Django 3.2.5 on 2022-01-20 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_scraprecipie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recipie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipies.scraprecipie'),
        ),
        migrations.AlterField(
            model_name='scraprecipie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scraprecipie',
            name='imageurl',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='scraprecipie',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
