# Generated by Django 3.2.5 on 2022-01-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20220120_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='recipie',
            new_name='scraprecipie',
        ),
    ]
