# Generated by Django 3.2.5 on 2022-01-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0005_rename_recipie_comments_scraprecipie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='scraprecipie',
        ),
        migrations.AddField(
            model_name='comments',
            name='recipie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipies.scraprecipie'),
        ),
    ]
