# Generated by Django 3.2.5 on 2022-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_alter_comments_recipie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likedrecipies',
            field=models.ManyToManyField(to='recipies.ScrapRecipie'),
        ),
    ]
